### ISSUE TITLE
COPI on markets is $0.03 and minswap has conversion at 1 COPI = 0.18 ADA which doesn't equal market price of $.54 for ADA

### ISSUE THREAD

**Issue by rob4949** [minswap/market-cap#10]
The current price of COPI token is $0.03 and I went to purchase this token, and on minswap it says that the price is .18ADA for 1 copi token. I purchased the ADA at $0.5416 per coin. If 1 copi token is 0.18 ADA, then that is $0.09 for a copi token
I appreciate your time and responses to help here. :-)
I looked up other tokens on Minswap and did the calculations and they come out to what the market prices are. I think something is incorrect with COPI in Minswap.
<img width="1379" alt="Screen Shot 2022-05-23 at 12 20 48 AM" src="https://user-images.githubusercontent.com/105922755/169749800-4eaf2161-d594-43a0-ad51-cd513eea4d35.png">
<img width="1137" alt="Screen Shot 2022-05-23 at 12 19 50 AM" src="https://user-images.githubusercontent.com/105922755/169749804-7af0b3a4-a9ea-4645-9b2c-8957529bca3a.png">

**Comment by longngn** [comment]
> The current price of COPI token is $0.03 and I went to purchase this token, and on minswap it says that the price is .18ADA for 1 copi token. I purchased the ADA at $0.5416 per coin. If 1 copi token is 0.18 ADA, then that is $0.09 for a copi token I appreciate your time and responses to help here. :-) I looked up other tokens on Minswap and did the calculations and they come out to what the market prices are. I think something is incorrect with COPI in Minswap. <img alt="Screen Shot 2022-05-23 at 12 20 48 AM" width="1379" src="https://user-images.githubusercontent.com/105922755/169749800-4eaf2161-d594-43a0-ad51-cd513eea4d35.png"> <img alt="Screen Shot 2022-05-23 at 12 19 50 AM" width="1137" src="https://user-images.githubusercontent.com/105922755/169749804-7af0b3a4-a9ea-4645-9b2c-8957529bca3a.png">

Hi, the COPI price on CoinMarketCap is from DEXes on BSC, so it's different from the market on Cardano (Minswap) because it's more difficult to arbitrage.
