### ISSUE TITLE
CI hits Blockfrost rate-limit

### ISSUE THREAD

**Issue by FractionEstate** [minswap/market-cap#122]
✕ test fetcher for token 1ddcb9c9de95361565392c5bdff64767492d61a96166cb16094e54be4f5054 (1579 ms)
    ✕ test fetcher for token b316f8f668aca7359ecc6073475c0c8106239bf87e05a3a1bd5697647856594649 (36 ms)
    ✕ test fetcher for token 2d92af60ee429bce238d3fd9f2531b45457301d74dad1bcf3f9d1dca564e4d (1027 ms)
    ✕ test fetcher for token 21abdf54f427b378fe9ba07419eff6e8e8fe0c5932e1fee2d3853b9350455045424c5545 (4 ms)
    ✓ test fetcher for token 7914fae20eb2903ed6fd5021a415c1bd2626b64a2d86a304cb40ff5e4c494649
    ✓ test fetcher for token 0d90046ad35546156aaf790525133f7fc713ca2790e397784b85f5c85554494c
    ✕ test fetcher for token a3931691f5c4e65d01c429e473d0dd24c51afdb6daf88e632a6c1e516f7263666178746f6b656e (1120 ms)

  ● supply fetchers › test fetcher for token 8daefa391220bd0d8d007f3748d870f7f3c106040314c8515ccc35a5464c4143

    BlockfrostServerError: 429: Too Many Requests

**Comment by longngn** [comment]
Possible solutions:
1. Use self-hosted runner so we don't share Github Actions' IP
2. Run tests sequentially instead of concurrently
