### ISSUE TITLE
Price on markets is .03 and minswap has the price at .18 ADA which doesn't equal market price

### ISSUE THREAD

**Issue by rob4949** [minswap/market-cap#9]
Hello, 
The current price of COPI token is .03 and i went to purchase this token, and on minswap it says that the price is .18 for 1 copi token. Is this wrong and will it be fixed
<img width="1379" alt="Screen Shot 2022-05-23 at 12 20 48 AM" src="https://user-images.githubusercontent.com/105922755/169742576-a983019a-e849-42ba-b1ca-9d10ae5e01c5.png">
<img width="1137" alt="Screen Shot 2022-05-23 at 12 19 50 AM" src="https://user-images.githubusercontent.com/105922755/169742581-221b58a4-b75c-4bc1-9534-4dd767593b87.png">
?

**Comment by longngn** [comment]
> Hello, The current price of COPI token is .03 and i went to purchase this token, and on minswap it says that the price is .18 for 1 copi token. Is this wrong and will it be fixed <img alt="Screen Shot 2022-05-23 at 12 20 48 AM" width="1379" src="https://user-images.githubusercontent.com/105922755/169742576-a983019a-e849-42ba-b1ca-9d10ae5e01c5.png"> <img alt="Screen Shot 2022-05-23 at 12 19 50 AM" width="1137" src="https://user-images.githubusercontent.com/105922755/169742581-221b58a4-b75c-4bc1-9534-4dd767593b87.png"> ?

0.03$ and 0.18 ADA, the currency is different

**Comment by rob4949** [comment]
Hello, 
I understand the currency is different, but this is my first time using Minswap and the calculations dont add up. I purchased the ADA at $0.5416 per coin. If 1 copi token is 0.18 ADA, then that equals $0.09 for a copi token and that is  much higher than the market price of COPI on the exchanges, which is at $.03.
I appreciate your time and responses to help here. :-)
